### PR TITLE
Worker hot reload

### PR DESCRIPTION
**Pull request by karolsojko**

### CODE REVIEW

**Comment by karolsojko** [comment]
@mobitar can you check this locally if it works for you? 

I keep getting crashes due to this:

```
syncing-server-js_1         | [nodemon] app crashed - waiting for file changes before starting...

```

**Comment by atmoio** [comment]
Testing now. Noticed I have to run `yarn install && yarn run build` and that `./server.sh update` wasn't enough to get it to build properly.

**Comment by atmoio** [comment]
No issues it seems:

```shell
syncing-server-js-worker_1  | db:3306 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | db (172.27.0.3:3306) open
syncing-server-js-worker_1  | db:3306 is up - executing command
syncing-server-js-worker_1  | cache (172.27.0.4:6379) open
syncing-server-js-worker_1  | cache:6379 is up - executing command
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js:3000 is unavailable yet - waiting for it to start
syncing-server-js-worker_1  | syncing-server-js (172.27.0.8:3000) open
syncing-server-js-worker_1  | syncing-server-js:3000 is up - executing command
syncing-server-js-worker_1  | Starting Worker in Local Mode...
syncing-server-js-worker_1  | yarn run v1.22.5
syncing-server-js-worker_1  | $ npx nodemon -L bin/worker.ts

syncing-server-js-worker_1  | [nodemon] 2.0.7
syncing-server-js-worker_1  | [nodemon] to restart at any time, enter `rs`
syncing-server-js-worker_1  | [nodemon] watching path(s): src/**/* bin/**/*
syncing-server-js-worker_1  | [nodemon] watching extensions: ts,json
syncing-server-js-worker_1  | [nodemon] starting `npx ts-node bin/worker.ts`

syncing-server-js-worker_1  | query: SELECT * FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'standard_notes_db' AND `TABLE_NAME` = 'migrations'
syncing-server-js-worker_1  | query: SELECT * FROM `migrations` `migrations`  ORDER BY `id` DESC
syncing-server-js-worker_1  | No migrations are pending
syncing-server-js-worker_1  | {"message":"Starting worker...","level":"info"}

```

**Comment by atmoio** [comment]
Ah, I was paying attention to the worker. Regular server also no issues:

```shell
syncing-server-js_1         | db:3306 is unavailable yet - waiting for it to start
syncing-server-js_1         | db (172.27.0.3:3306) open
syncing-server-js_1         | db:3306 is up - executing command
syncing-server-js_1         | cache (172.27.0.4:6379) open
syncing-server-js_1         | cache:6379 is up - executing command
syncing-server-js_1         | Starting Web in Local Mode...
syncing-server-js_1         | yarn run v1.22.5
syncing-server-js_1         | $ npx nodemon -L bin/server.ts
syncing-server-js_1         | [nodemon] 2.0.7
syncing-server-js_1         | [nodemon] to restart at any time, enter `rs`
syncing-server-js_1         | [nodemon] watching path(s): src/**/* bin/**/*
syncing-server-js_1         | [nodemon] watching extensions: ts,json
syncing-server-js_1         | [nodemon] starting `npx ts-node bin/server.ts`
...
syncing-server-js_1         | {"message":"Server started on port 3000","level":"info"}
```

**Comment by karolsojko** [comment]
closing as outdated.

**Pull request closed without merging**
